"""initial_schema

Revision ID: 0b4557742746
Revises: 
Create Date: 2026-03-03 18:05:39.722368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4557742746'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('head_sha', sa.String(), nullable=True),
    sa.Column('base_sha', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'repo', 'pr_number')
    )
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_requests_id'), ['id'], unique=False)

    op.create_table('review_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_instances_id'), ['id'], unique=False)

    op.create_table('review_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_instance_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('walkthrough', sa.Text(), nullable=True),
    sa.Column('chunk_summary', sa.Text(), nullable=True),
    sa.Column('review_order', sa.Text(), nullable=True),
    sa.Column('file_paths', sa.Text(), nullable=True),
    sa.Column('diff_content', sa.Text(), nullable=True),
    sa.Column('line_map', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ai_suggestions_md', sa.Text(), nullable=True),
    sa.Column('ai_comments_json', sa.Text(), nullable=True),
    sa.Column('human_done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['review_instance_id'], ['review_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_chunks_id'), ['id'], unique=False)

    op.create_table('review_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_instance_id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('diff_hunk', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('in_reply_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_instance_id'], ['review_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_threads_id'), ['id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_chunk_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_chunk_id'], ['review_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)

    op.create_table('draft_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_chunk_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('start_side', sa.String(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('github_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_chunk_id'], ['review_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_comments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_comments_id'))

    op.drop_table('draft_comments')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('review_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_threads_id'))

    op.drop_table('review_threads')
    with op.batch_alter_table('review_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_chunks_id'))

    op.drop_table('review_chunks')
    with op.batch_alter_table('review_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_instances_id'))

    op.drop_table('review_instances')
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_requests_id'))

    op.drop_table('pull_requests')
    # ### end Alembic commands ###
