"""add_review_request_cache

Revision ID: 6fca07df826e
Revises: 9970c026bb25
Create Date: 2026-03-03 19:18:02.394865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fca07df826e'
down_revision: Union[str, Sequence[str], None] = '9970c026bb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_request_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('repo_full_name', sa.String(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('labels_json', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_url')
    )
    with op.batch_alter_table('review_request_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_request_cache_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_request_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_request_cache_id'))

    op.drop_table('review_request_cache')
    # ### end Alembic commands ###
