"""add_thread_position_resolved_and_re_reviews

Revision ID: 94eacd111d09
Revises: 6fca07df826e
Create Date: 2026-03-03 19:39:25.259654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94eacd111d09'
down_revision: Union[str, Sequence[str], None] = '6fca07df826e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('re_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_instance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('old_head_sha', sa.String(), nullable=True),
    sa.Column('new_head_sha', sa.String(), nullable=True),
    sa.Column('changes_summary_md', sa.Text(), nullable=True),
    sa.Column('thread_opinions_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_instance_id'], ['review_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('re_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_re_reviews_id'), ['id'], unique=False)

    with op.batch_alter_table('review_threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_threads', schema=None) as batch_op:
        batch_op.drop_column('is_resolved')
        batch_op.drop_column('position')

    with op.batch_alter_table('re_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_re_reviews_id'))

    op.drop_table('re_reviews')
    # ### end Alembic commands ###
