"""add_pr_state_and_review_decision

Revision ID: 9970c026bb25
Revises: a904c1266c2c
Create Date: 2026-03-03 18:54:50.564963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9970c026bb25'
down_revision: Union[str, Sequence[str], None] = 'a904c1266c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('review_decision', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_column('review_decision')
        batch_op.drop_column('pr_state')

    # ### end Alembic commands ###
