"""add_label_to_draft_comments

Revision ID: a904c1266c2c
Revises: 0b4557742746
Create Date: 2026-03-03 18:44:56.466775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a904c1266c2c'
down_revision: Union[str, Sequence[str], None] = '0b4557742746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
